### ISSUE TITLE
Backend server is not running Getting Error 

### ISSUE THREAD

**Issue by ghousethanedar** [Coding-Crashkurse/Udemy-Advanced-LangChain#1]
When we run the docker-compose up 
Command 

all 5 container get created 
but backend container is not running 
its showing the error 
exec /wait-for-postgres.sh: no such file or directory

seems all the frontend functionalities are not working because backend container is not working 
could you please help to resolve this.

**Comment by wassay13** [comment]
> When we run the docker-compose up 
> 
> Command 
> 
> 
> 
> all 5 container get created 
> 
> but backend container is not running 
> 
> its showing the error 
> 
> exec /wait-for-postgres.sh: no such file or directory
> 
> 
> 
> seems all the frontend functionalities are not working because backend container is not working 
> 
> could you please help to resolve this.

Change Line Sequence from CRLF to LF in /wait-for-postgres.sh file. 

In VsCode it's present in lower right corner, beside UTF-8 encoding.
